### ISSUE TITLE
[feature request] Include default values in generated markdown

### ISSUE THREAD

**Issue by patpicos** [Kavinraja-G/crossplane-docs#10]
Following the terraform-docs model, it would be useful for consumers to see the default values configured on XRD attributes

<img width="378" alt="image" src="https://github.com/user-attachments/assets/5e02ffeb-3b9e-4149-9784-8dbccf69f500">

**Comment by Kavinraja-G** [comment]
Thanks @patpicos  for the suggestion! This will be included in the upcoming relase 🚀
