### ISSUE TITLE
[feature request] Separate inputs from outputs in markdown

### ISSUE THREAD

**Issue by patpicos** [Kavinraja-G/crossplane-docs#9]
It would be good if the generated markdown was to have separate tables for the inputs and outputs (`status`), similar to how `terraform-docs` splits `variable` from `output` as shown below

<img width="400" alt="image" src="https://github.com/user-attachments/assets/a2bef9f5-d51c-4a6d-93ec-71f98a289975">

**Comment by Kavinraja-G** [comment]
Thanks for the feedback again! That's a good idea to include `status` as an Output. 

Here you go:
<img width="942" alt="image" src="https://github.com/user-attachments/assets/e37455f0-dae1-4a28-ba10-98d9604e35b6" />
